package kiu.oto.common.inputs.enums;

public enum RuleName {
    NO_RULE, NO_REPETITION, NO_REPETITION_X3, NO_OPPOSITE,
    NO_CLOCKWISE_NEIGHBOR, NO_REPETITION_TWO_BEFORE,
    NO_OPPOSITE_TWO_BEFORE, NO_NEIGHBOUR_IF_LAST_TWO_SAME,
    NO_NEIGHBOUR_IF_LAST_THREE_SAME;

}
